---
- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker-archive-keyring.gpg
    mode: '0644'
  become: true

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    #repo: deb https://download.docker.com/linux/debian trixie stable
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian trixie stable"
    state: present
    filename: docker
  become: true  

- name: Install Docker Engine, Docker CLI, Containerd, & Docker Compose
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: present
    install_recommends: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Set Docker Registry Proxy Configuration
  ansible.builtin.copy:
    dest: "/etc/docker/daemon.json"
    content: |
      {
              "metrics-addr": "127.0.0.1:9323",
              "experimental": true
      }
